---
title: "linear_models"
author: "Kimia Faroughi"
date: "2025-11-06"
output: github_document
---

Load packages 

```{r}
library(tidyverse)
library(p8105.datasets)
```

Import data

```{r}
data("nyc_airbnb")
```

Look at the data / do some cleaning

```{r}
nyc_airbnb =
  nyc_airbnb |> 
  mutate(
    stars = review_scores_location / 2
  ) |> 
  rename (
    borough = neighbourhood_group
  ) |> 
  filter(borough != "Staten Island") |> 
  select(price, stars, borough, room_type, neighbourhood)
```

Do some additional cleaning then fit linear regression model

```{r}
nyc_airbnb = 
  nyc_airbnb |> 
  mutate(
    borough = fct_infreq(borough), #orders in descending order of frequency, needs to be factor for regression to work
    room_type = fct_infreq(room_type)
  )

fit = lm(price ~ stars + borough, data = nyc_airbnb)
```

Look at `lm` stuff

```{r, eval = FALSE}
#don't recommend doing this, super messy output
summary(fit)
names(summary(fit))
summary(fit)[["coefficients"]]
summary(fit)[["df"]]

fitted.values(fit)
```

Look at cleaner `lm` stuff

```{r}
fit |> 
  broom::tidy() |> 
  mutate(
    term = str_replace(term, "borough", "Borough: ")
  ) |> 
  select(term, estimate, p.value) |> 
  knitr::kable(digits = 3)
```

